Mobile menu
calvnce/portfolio pull request #13
Opened 2021-06-23 23:16 UTC by calvnce

2021-06-23 23:30 UTC, smcommits requested changes
Hi @calvnce, 

### You have done an excellent job. The project appears to be fantastic. It reflects great efforts and good understanding. 
### To make this project even better, there are some issues that you still need to work on. You are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


 ## Required Changes ♻️
_Please check the inline comments below._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-23 23:30 UTC, smcommits commented on dist/js/script.js
> +  const nav = classItem('.desktop-menu');
- [ ]  **Please make sure that the user click (or tap) any option of the mobile menu, the mobile menu disappear. Also, make sure that the links are working**

This is the default behavior in mobile menus. As soon as a link is clicked, the menu should close and the user should be taken on the respective link. Please implement this.

2021-06-23 23:30 UTC, smcommits commented on dist/js/script.js
> +  const nav = classItem('.desktop-menu');
- [ ] **Please make sure that the menu matches the original design from Figma.**

The menu in original design spans over the entire height of the viewport. Please modify your menu to match the original design 

Cloned Design|Orginal Design
:------------------:|:-------------------:
![image](https://user-images.githubusercontent.com/59168430/123180401-cf278500-d4a8-11eb-8328-2327a5792900.png)|![image](https://user-images.githubusercontent.com/59168430/123180453-ed8d8080-d4a8-11eb-962a-8b4c18219a70.png)

2021-06-23 23:41 UTC, smcommits commented
@calvnce A mistake has been made and this review has been marked as "Approved". I am extremely about this. Please don't submit the project as the project will be marked as "Requested Changes" as soon as possible. Again, sorry for the accident. Please feel free to leave a comment if you need any clarification.

2021-06-24 10:45 UTC, calvnce commented
This `Pull request` updates the required changes on the mobile menu interactivity

2021-06-24 11:05 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @calvnce     ! :wave: :wave:

#### You have done really well in implementing the previously required changes.

 However, there are changes required for you to make in order for this project to be approved. 

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. :smile:

- - -

### **Required Changes** ♻️

- [ ] Kindly add a descriptive Pull Request Message with a descriptive title as well. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. You currently have a comment underneath the first review. Please add the PR message at the top where the description of what you've done in this milestone should be.

_See the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 1 more review as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-06-24 11:05 UTC, Temmarie commented on dist/js/script.js
> +  const nav = classItem('.desktop-menu');
- [ ] As requested by the previous code reviewer, make sure the menu and other parts of the page matches the original design. 
_See images below._

**Original** | **Your clone**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/123251830-7ce26600-d4a0-11eb-96fa-9f6b6519d37d.png) | ![image](https://user-images.githubusercontent.com/49621279/123252029-aac7aa80-d4a0-11eb-8709-b5aaf10425f1.png)
![image](https://user-images.githubusercontent.com/49621279/123252120-cc289680-d4a0-11eb-9a83-a058c5c13744.png) | ![image](https://user-images.githubusercontent.com/49621279/123252185-dd71a300-d4a0-11eb-9506-43ff4bf47b0d.png)

2021-06-24 15:13 UTC, merged